# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '1.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys

class Ui_Planirovhik(object):
    def setupUi(self, Planirovhik):
        Planirovhik.setObjectName("Planirovhik")
        Planirovhik.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Planirovhik)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 571, 611))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(640, 540, 88, 34))
        self.pushButton.setObjectName("pushButton")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(573, 2, 231, 371))
        self.textEdit.setObjectName("textEdit")
        Planirovhik.setCentralWidget(self.centralwidget)

        self.retranslateUi(Planirovhik)
        QtCore.QMetaObject.connectSlotsByName(Planirovhik)

        self.add_func()


    def add_func(self):
        self.pushButton.clicked.connect(self.add_label_and_checkbox)
        self.layout = QtWidgets.QVBoxLayout(self.centralwidget)



    def retranslateUi(self, Planirovhik):
        _translate = QtCore.QCoreApplication.translate
        Planirovhik.setWindowTitle(_translate("Planirovhik", "Планировщик"))
        self.pushButton.setText(_translate("Planirovhik", "Добавить"))


    def add_label_and_checkbox(self):
         
        if self.textEdit.toPlainText().strip() != "":
            h_layout = QtWidgets.QHBoxLayout() 
            label = QtWidgets.QLabel(self.textEdit.toPlainText())
            checkbox = QtWidgets.QCheckBox()

            h_layout.addWidget(label)
            h_layout.addWidget(checkbox)

            self.layout.addLayout(h_layout)
            self.textEdit.clear()
        else:
            pass



if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_Planirovhik()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())